sudo: required
language: generic

services: 
  - docker
before_install:
  - docker build -t sumanth/Complex -f ./client/Dockerfile.dev ./client
# script:
#   - docker run sumanth/dockernodereact npm test -- --coverage
after_success:
  - docker build -t sumanth/multiclient ./client
  - docker build -t sumanth/multinginx ./nginx
  - docker build -t sumanth/multiserver ./server
  - docker build -t sumanth/multiworker ./worker

  #log in to docker cli

  - echo "$DOCKER_PW" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push sumanth/multiclient
  - docker push sumanth/multinginx
  - docker push sumanth/multiserver
  - docker push sumanth/multiworker
