sudo: required
language: generic

services: 
  - docker

before_install:
  - docker build -t sumanthgowda/complex -f ./client/Dockerfile.dev ./client
# script:
#   - docker run sumanth/dockernodereact npm test -- --coverage
after_success:
  - docker build -t sumanthgowda/multiclient ./client
  - docker build -t sumanthgowda/multinginx ./nginx
  - docker build -t sumanthgowda/multiserver ./server
  - docker build -t sumanthgowda/multiworker ./worker

  #log in to docker cli

  - echo "$DOCKER_PW" | docker login -u "$DOCKER_ID" --password-stdin docker.io

  - docker push sumanthgowda/multiclient
  - docker push sumanthgowda/multinginx
  - docker push sumanthgowda/multiserver
  - docker push sumanthgowda/multiworker
